# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  # Stage: Build
  build_dependancies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies..."

  build_linter:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running linters..."

  build_packaging:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning and Packaging..."

  build_validation:
    executor: node/default
    steps:
      - checkout
      - run: echo "Build step is all good"

  # Stage: Tests
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/

  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running integration tests..."

  regression_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running regression tests..."

  performance_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running performance tests..."

  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running security tests..."

  compatibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running compatibility tests..."

  accessibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running accessibility tests..."

  tests_validation:
    executor: node/default
    steps:
      - checkout
      - run: echo "Tests step is all good"

  # Stage: Deploy
  prepare_deployment:
    executor: node/default
    steps:
      - checkout
      - run: echo "Preparing deployment environment..."

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_release:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to release environment..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

  verify_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running verification tests..."

  functional_validation:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running functional validation tests..."

  load_testing:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running load tests..."

  monitor_and_follow_up:
    executor: node/default
    steps:
      - checkout
      - run: echo "Monitoring and following up deployment..."

workflows:
  version: 2
  build_and_test:
    jobs:
      # Build
      - build_dependancies
      - build_linter
      - build_packaging:
          requires:
            - build_dependancies
      - build_validation:
          requires:
            - build_dependancies
            - build_linter
            - build_packaging
      # Tests
      - unit_tests:
          requires:
            - build_validation
      - integration_tests:
          requires:
            - build_validation
      - regression_tests:
          requires:
            - build_validation
      - performance_tests:
          requires:
            - build_validation
      - security_tests:
          requires:
            - build_validation
      - compatibility_tests:
          requires:
            - build_validation
      - accessibility_tests:
          requires:
            - build_validation
      - tests_validation:
          requires:
            - unit_tests
            - integration_tests
            - regression_tests
            - performance_tests
            - security_tests
            - compatibility_tests
            - accessibility_tests
      # Deploy
      - prepare_deployment:
          requires:
            - tests_validation
      - verify_tests:
          requires:
            - tests_validation
      - functional_validation:
          requires:
            - tests_validation
      - load_testing:
          requires:
            - tests_validation
      - deploy_dev:
          requires:
            - tests_validation
            - prepare_deployment
            - verify_tests
            - functional_validation
            - load_testing
          filters:
            branches:
              only:
                - develop
      - deploy_release:
          requires:
            - tests_validation
            - prepare_deployment
            - verify_tests
            - functional_validation
            - load_testing
          filters:
            branches:
              only:
                - /^release\/.*/
      - deploy_prod:
          requires:
            - tests_validation
            - prepare_deployment
            - verify_tests
            - functional_validation
            - load_testing
          filters:
            branches:
              only:
                - main
      - monitor_and_follow_up:
          requires:
            - tests_validation
            - deploy_dev
            - deploy_release
            - deploy_prod