# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  # Stage: Build
  build_dependancies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies..."
  
  build_linter:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running linters..."
  
  build_packaging:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning and Packaging..."
  
  # Stage: Tests
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
  
  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running integration tests..."
  
  regression_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running regression tests..."
  
  performance_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running performance tests..."
  
  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running security tests..."
  
  compatibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running compatibility tests..."
  
  accessibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running accessibility tests..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
      # - deploy_dev:
      #     requires:
      #       - unit_tests
      #     filters:
      #       branches:
      #         only:
      #           - develop

      # - deploy_prod:
      #     requires:
      #       - unit_tests
      #     filters:
      #       branches:
      #         only:
      #           - main
